CREATE TABLE IF NOT EXISTS Users (
    `user_id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE,
    `username` VARCHAR(25) NOT NULL UNIQUE,
    `salt` VARCHAR(255) NOT NULL,
    `password_hash` VARCHAR(255) NOT NULL,
    `pfp_filename` VARCHAR(255) NOT NULL,
    `last_updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `datetime_created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) AUTO_INCREMENT = 1;

-- CREATE TABLE IF NOT EXISTS Admins (
--     `user_id` INT NOT NULL,
--     `datetime_created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

-- ) AUTO_INCREMENT = 1;